name: CI


on: [push, workflow_dispatch]


jobs:

  build:


    runs-on: ubuntu-latest


    steps:

    - name: permissions

      run: sudo chmod +x $ { { github.workspace }}/install_xrdp.sh && sudo chmod +x $ { { github.workspace }}/install_ngrok.sh

    - name: Extract

      run: $ { { github.workspace }}/install_ngrok.sh && $ { { github.workspace }}/install_xrdp.sh

    - name: Create Tunnel

      run: ngrok tcp 3389
