name: CI


on: [push, workflow_dispatch]


jobs:

  build:


    runs-on: ubuntu-latest


    steps:

    - name: permissions

      run: sudo chmod +x install_xrdp.sh && sudo chmod +x install_ngrok.sh

    - name: Extract

      run: ./install_ngrok.sh && ./install_xrdp.sh

    - name: Create Tunnel

      run: ngrok tcp 3389
